language: python
dist: xenial
services:
  - xvfb
python:
  - 3.7
sudo: false
addons:
  apt_packages:
    - pandoc
cache:
  pip: true
  directories:
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools
  - nvm install 8
  - pip install cookiecutter
install:
  - pushd $(mktemp -d)
  - cookiecutter $TRAVIS_BUILD_DIR --config-file $TRAVIS_BUILD_DIR/tests/testconfig.yaml --no-input
  - pushd jupyter-widget-testwidgets
  - pip install --upgrade -v -e ".[test, examples, docs]"
before_script:
  - |
    export CHROME_BIN=chromium-browser
script:
  - py.test
  - pushd ts
  - npm test
  - popd
  # Check docs can be build + links
  - pushd docs
  - make html
  - make linkcheck
  - popd
  # Make a non-local install so the data_files get populated
  - pip uninstall -y ipywidgettestwidgets
  - pip install .
  - jupyter nbextension enable --py --sys-prefix ipywidgettestwidgets
  # Validate nbextension (enable does not use exit code):
  - python -c "from notebook.nbextensions import validate_nbextension; import sys; sys.exit(validate_nbextension('ipywidgettestwidgets/extension') or 0)"
  - pip install jupyterlab
  # Make sure our lab extension was installed.
  - jupyter labextension list
  - jupyter labextension list 2>&1 | grep -q jupyter-widget-testwidgets
  # Make sure our lab extension can be linked.
  - jupyter labextension link
  - popd
  - popd
