version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub

python:
  version: 3.7
  install:
  - method: pip
    path: .
    extra_requirements:
    - examples
    - docs
conda:
  environment: docs/environment.yml
